# Generated by Django 3.0.7 on 2020-07-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_auto_20200624_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0999999999', help_text='phone number of the student', max_length=10, verbose_name='phone number'),
        ),
    ]
